liquibase:
    change-log: classpath:/db/changelog/liquibase-changelog.xml

mots:
    ivrApiKey: ${ivrApiKey}
    resourceId: mots
    loadLocations: ${loadLocations}

security:
    oauth2:
        client:
            authentication-scheme: header

token:
    validitySeconds: 600

server:
    port: ${tomcatServerPort}
    ssl:
        enabled: ${sslEnabled}
        key-alias: ${keyAlias}
        key-store: ${keyStore}
        key-store-password: ${keyStorePassword}
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        password: ${databasePassword}
        url: ${databaseUrl}
        username: ${databaseUser}
        type: com.zaxxer.hikari.HikariDataSource
    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: false
